trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'
  name: GuidelineAWS

variables:
  imageName: 'amitnd/sample-app'
  imageTag: '$(Build.BuildId)'

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'Docker Hub'
      repository: $(imageName)
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: $(imageTag)
    displayName: 'Docker Build and Push'

  - task: HelmInstaller@1

  - script: |
      helm upgrade --install sample-app ./sample-app --set image.tag=$(imageTag)
    displayName: 'Deploy to Minikube'