trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'
  name: GuidelineAWS

variables:
  imageName: 'amitnd/sample-app'
  imageTag: '$(Build.BuildId)'

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'Docker Hub'
      repository: $(imageName)
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: $(imageTag)
    displayName: 'Docker Build and Push'

  - script: |
      git fetch origin
      git checkout -b main 
      sed -i 's|image:\s*".*"$|image: "$(imageTag)"|g' ./sample-app/values.yaml
      git status
      git add .
      git commit -m "Update Docker image tag to $(imageTag)"
      git push origin main
    displayName: 'Update and Commit values.yaml'
