trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'
  name: GuidelineAWS

variables:
  imageName: 'amitnd/sample-app'
  imageTag: '$(Build.BuildId)'

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'Docker Hub'
      repository: $(imageName)
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: $(imageTag)
    displayName: 'Docker Build and Push'

  - checkout: self

  - script: |
      sed -i 's|image: ".*"|image: "$(imageTag)"|g' sample-app/values.yaml
      git status  # Verify changes
      git add sample-app/values.yaml  # Stage the changes
      git commit -m "Update Docker image tag to $(imageTag)"  # Commit changes
      git push https://$(GitHubToken)@github.com/$(GitHubOwner)/$(GitHubRepo).git HEAD:main
    displayName: 'Update and Commit values.yaml'