trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'
  name: GuidelineAWS

variables:
  imageName: 'amitnd/sample-app'
  tag: '$(Build.BuildId)'

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'Docker Hub'
      repository: $(imageName)
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
    displayName: 'Docker Build and Push'

  - checkout: self

  - script: |
      echo "Updating image tag in values.yaml"
      sed -i 's/image.tag: .*/image.tag: "$(tag)"/' sample-app/values.yaml 
      git add sample-app/values.yaml
      git commit -m "Update Docker image tag to $(tag)"
      git push origin main
    displayName: 'Update Git repository with new image tag'