replicaCount: 2

image:
  repository: amitnd/sample-app
  pullPolicy: IfNotPresent
  tag: 49

service:
  type: LoadBalancer 
  port: 5000
  targetPort: 5000
  name: sample-app-lb

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "250m"

livenessProbe:
  tcpSocket:
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 5
    
readinessProbe:
  httpGet:
    path: /api/v1/foods
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75

serviceAccount:
  create: false

environment:
  DOTNET_ENVIRONMENT: Development